name: deploy-container

on: 
  push: 
    branches: 
      - main
    paths:
      - 'react-micro-frontends/mfe/container/**'

defaults:
  run:
    working-directory: react-micro-frontends/mfe/container

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
